services:
  bff-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bff-java-service
    ports:
      - "8085:8085"
    environment:
      - APP_NAME=${APP_NAME}
      - SECURITY_USER=${SECURITY_USER}
      - SECURITY_PASS=${SECURITY_PASS}
      - ERP_DB_URL=${ERP_DB_URL}
      - ERP_DB_USER=${ERP_DB_USER}
      - ERP_DB_PASS=${ERP_DB_PASS}
      - RADIUS_DB_URL=${RADIUS_DB_URL}
      - RADIUS_DB_USER=${RADIUS_DB_USER}
      - RADIUS_DB_PASS=${RADIUS_DB_PASS}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FILE_PATH=${LOG_FILE_PATH}
      - QRCODE_PASSWORD=${QRCODE_PASSWORD}
      - SERVER_PORT=8085
    depends_on:
      - redisjava
    volumes:
      - ./meus-logs:/app/logs

  redisjava:
    image: redis:alpine
    container_name: redisjava