services:
  bff-app:
    image: sebratel/bff-sebratel:latest
    container_name: bff-java-service
    restart: unless-stopped
    ports:
      - "8086:8085"
    depends_on:
      - kafka
    networks:
      - proxy
      - default
    environment:
      # Aplicação
      - APP_NAME=bff
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}

      # Segurança
      - SECURITY_USER=${SECURITY_USER}
      - SECURITY_PASS=${SECURITY_PASS}

      # Banco ERP (PostgreSQL)
      - ERP_DB_URL=${ERP_DB_URL}
      - ERP_DB_USER=${ERP_DB_USER}
      - ERP_DB_PASS=${ERP_DB_PASS}

      # Banco Radius (PostgreSQL)
      - RADIUS_DB_URL=${RADIUS_DB_URL}
      - RADIUS_DB_USER=${RADIUS_DB_USER}
      - RADIUS_DB_PASS=${RADIUS_DB_PASS}

      # Redis (já existente no ambiente)
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

      # Logs
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE_PATH=${LOG_FILE_PATH:-logs/bff.log}

      # MariaDB
      - AFETADOS_DB_URL=${AFETADOS_DB_URL}
      - AFETADOS_DB_USER=${AFETADOS_DB_USER}
      - AFETADOS_DB_PASS=${AFETADOS_DB_PASS}

      # Usuario Integrador Elleven
      - ELLEVEN_CLIENT_ID=${ELLEVEN_CLIENT_ID}
      - ELLEVEN_CLIENT_SECRET=${ELLEVEN_CLIENT_SECRET}
      - ELLEVEN_CLIENT_SYNDATA=${ELLEVEN_CLIENT_SYNDATA}
      - ELLEVEN_CLIENT_GRANT_TYPE=${ELLEVEN_CLIENT_GRANT_TYPE}
      - ELLEVEN_CLIENT_SCOPE=${ELLEVEN_CLIENT_SCOPE}

      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CLIENT_SCOPE=${GOOGLE_CLIENT_SCOPE}

    volumes:
      - bff-logs:/app/logs

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - default

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - default

volumes:
  bff-logs:
    driver: local

# Declaração das redes
networks:
  proxy:
    external: true
  default:
    driver: bridge
