services:
  bff-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bff-java-service
    ports:
      - "8085:8085"
    environment:
      - SELENIUM_URL=http://chrome-node:4444/wd/hub
      - APP_NAME=${APP_NAME}
      - SECURITY_USER=${SECURITY_USER}
      - SECURITY_PASS=${SECURITY_PASS}
      - ERP_DB_URL=${ERP_DB_URL}
      - ERP_DB_USER=${ERP_DB_USER}
      - ERP_DB_PASS=${ERP_DB_PASS}
      - RADIUS_DB_URL=${RADIUS_DB_URL}
      - RADIUS_DB_USER=${RADIUS_DB_USER}
      - RADIUS_DB_PASS=${RADIUS_DB_PASS}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redisjava
      - REDIS_PORT=6379
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FILE_PATH=${LOG_FILE_PATH}
      - QRCODE_PASSWORD=${QRCODE_PASSWORD}
      - ELLEVEN_CLIENT_ID=${ELLEVEN_CLIENT_ID}
      - ELLEVEN_CLIENT_SECRET=${ELLEVEN_CLIENT_SECRET}
      - ELLEVEN_CLIENT_SYNDATA=${ELLEVEN_CLIENT_SYNDATA}
      - ELLEVEN_CLIENT_GRANT_TYPE=${ELLEVEN_CLIENT_GRANT_TYPE}
      - ELLEVEN_CLIENT_SCOPE=${ELLEVEN_CLIENT_SCOPE}
      - AFETADOS_DB_URL=${AFETADOS_DB_URL}
      - AFETADOS_DB_USER=${AFETADOS_DB_USER}
      - AFETADOS_DB_PASS=${AFETADOS_DB_PASS}
      - SERVER_PORT=8085
    depends_on:
      - redisjava
      - chrome-node
    volumes:
      - ./meus-logs:/app/logs
      - ./python-logs:/var/log/app_python.log

  chrome-node:
    image: selenium/standalone-chrome:latest
    container_name: chrome-node
    shm_size: '2gb' # Essencial para evitar o "DevToolsActivePort" crash

  redisjava:
    image: redis:alpine
    container_name: redisjava
    ports:
      - "6379:6379"
