spring.application.name=${APP_NAME:bff}
server.port=${SERVER_PORT:8085}
spring.security.user.name=${SECURITY_USER}
spring.security.user.password=${SECURITY_PASS}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.mvc.async.request-timeout=600000
server.tomcat.connection-timeout=600000
spring.datasource.erp.url=${ERP_DB_URL}
spring.datasource.erp.username=${ERP_DB_USER}
spring.datasource.erp.password=${ERP_DB_PASS}
spring.datasource.erp.driver-class-name=org.postgresql.Driver
spring.datasource.afetados.url=${AFETADOS_DB_URL}
spring.datasource.afetados.username=${AFETADOS_DB_USER}
spring.datasource.afetados.password=${AFETADOS_DB_PASS}
spring.datasource.afetados.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.radius.url=${RADIUS_DB_URL}
spring.datasource.radius.username=${RADIUS_DB_USER}
spring.datasource.radius.password=${RADIUS_DB_PASS}
spring.datasource.radius.driver-class-name=org.postgresql.Driver

spring.datasource.dho.url=${DHO_DB_URL:jdbc:mariadb://10.0.11.171/DHO_Application}
spring.datasource.dho.username=${DHO_DB_USER:DevSebratel}
spring.datasource.dho.password=${DHO_DB_PASS:DevBI*24}
spring.datasource.dho.driver-class-name=org.mariadb.jdbc.Driver

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=alpha
logging.level.root=${LOG_LEVEL:INFO}
logging.level.br.com.sebratel.bff.service=INFO
logging.file.name=${LOG_FILE_PATH:logs/bff.log}
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{0} - %msg%n

elleven.client-id=${ELLEVEN_CLIENT_ID:}
elleven.client-secret=${ELLEVEN_CLIENT_SECRET:}
elleven.syndata=${ELLEVEN_CLIENT_SYNDATA:}
elleven.grant-type=${ELLEVEN_CLIENT_GRANT_TYPE:}
elleven.scope=${ELLEVEN_CLIENT_SCOPE:}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.scope=${GOOGLE_CLIENT_SCOPE:}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://www.googleapis.com/oauth2/v3/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG

# Kafka Configuration
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.group-id=bff-group
spring.kafka.consumer.properties.spring.json.trusted.packages=br.com.sebratel.bff.dto

dho.api.url=${DHO_API_URL:http://localhost:8081}
