spring.application.name=${APP_NAME:bff}

server.port=${SERVER_PORT:8085}

spring.security.user.name=${SECURITY_USER}
spring.security.user.password=${SECURITY_PASS}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.mvc.async.request-timeout=600000

# erp
spring.datasource.erp.url=${ERP_DB_URL}
spring.datasource.erp.username=${ERP_DB_USER}
spring.datasource.erp.password=${ERP_DB_PASS}
spring.datasource.erp.driver-class-name=org.postgresql.Driver

# radius
spring.datasource.radius.url=${RADIUS_DB_URL}
spring.datasource.radius.username=${RADIUS_DB_USER}
spring.datasource.radius.password=${RADIUS_DB_PASS}
spring.datasource.radius.driver-class-name=org.postgresql.Driver

# redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:8301}

# spring doc
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=alpha

# logs
logging.level.root=${LOG_LEVEL:INFO}
logging.level.br.com.sebratel.bff.service=DEBUG
logging.file.name=${LOG_FILE_PATH:logs/bff.log}
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
